[package]
name = "beam"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.179"
rmp-serde = "1.3.1"
serde = { version = "1.0.228", features = ["derive", "alloc", "rc", "serde_derive"] }

[profile.release]
debug = true
